### ISSUE TITLE
[SPIKE][Document] Utility (M3) Specification - Fisherman

### ISSUE THREAD

**Issue by jessicadaugherty** [pokt-network/pocket-network-protocol#18]
## Objective

Descope and update specifications of M3 - MVP (initial launch) of Pocket-specific utility.

This includes, but is not necessarily limited to:

- Differentiating which protocol level actors (i.e. Fisherman) are permissionless vs. permissioned
- How Fisherman interact with the portal/applications/nodes etc.
- (Stretch) Defining how app usage is tracked & counted

The goal is to update the V1 roadmap, timelines, documentation, etc. accordingly.

## Origin Document

The original utility spec was captured across several conversations compiled [here](https://drive.google.com/drive/folders/1IysQhNF0Wv0tZBmwdRpJ-Hv6osk_21bs)

More recent discussions about the utility spec can be found [here](https://www.notion.so/pocketnetwork/9e0590bdbd754163a5e7905f2246892c?v=ad14b5c982384c99944b153692c18f33&p=ed52b1c164dd4671a7e2682b46426633&pm=s)

## Goals

- Update the Fisherman specification in [pocket-network-protocol](https://github.com/pokt-network/pocket-network-protocol)/utility/

## Deliverable

- Answer whether or not we are using Fisherman as a permissioned or permissionless actor on launch of V1 with tradeoffs outlined:
   - How do we breakout permissioned aspect of Fisherman in the future?
   - Can there be more than one trusted Fisherman?
   - How does permissioned Fisherman impact Portal Development?  
   - Timeline impacts of permissioned vs permissionless Fisherman

# Nice to Haves
- Updated spec doc (fisherman)
- New mermaid diagrams, where applicable, to improve readability & understanding
- New latex algorithms, if applicable, to understand utility related algorithms
- Update list of items in milestone 15

## Non-goals / Non-deliverables

- Implementing V1 utility code

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

---

**Creator**: @jessicadaugherty

**Comment by Olshansk** [comment]
Notes from internal team meeting available as a reference: https://www.notion.so/pocketnetwork/2022-11-29-97f8d9f73cbb4f03979eb4714710c5b2

**Comment by jessicadaugherty** [comment]
Rework this into fisherman and AAT deliverable tickets

**Comment by jessicadaugherty** [comment]
Rework this into fisherman and AAT deliverable tickets
