### ISSUE TITLE
[SPIKE][Document] Utility (M3) Specification - Application Protocol

### ISSUE THREAD

**Issue by jessicadaugherty** [pokt-network/pocket-network-protocol#22]
## Objective

Descope and update specifications of M3 - MVP (initial launch) of Application Pocket-specific utility.

This includes, but is not necessarily limited to:

- The application lifecycle (staking to network participation)
   - Staking initiations and modifications
   - ABR

The goal is to update the V1 roadmap, timelines, documentation, etc. accordingly.

## Origin Document

The original utility spec was captured across several conversations compiled [here](https://drive.google.com/drive/folders/1IysQhNF0Wv0tZBmwdRpJ-Hv6osk_21bs)

More recent discussions about the utility spec can be found [here](https://www.notion.so/pocketnetwork/9e0590bdbd754163a5e7905f2246892c?v=ad14b5c982384c99944b153692c18f33&p=ed52b1c164dd4671a7e2682b46426633&pm=s)

[Application Protocol Specification](https://github.com/pokt-network/pocket-network-protocol/tree/main/utility#34-application-protocol)

## Goals

- Update the Application specification in [pocket-network-protocol](https://github.com/pokt-network/pocket-network-protocol)/utility/

## Deliverable

- [ ] Updated spec doc
- [ ] New mermaid diagrams, where applicable, to improve readability and understanding
- [ ] Updated milestones, if applicable

## Non-goals / Non-deliverables

- Documenting or Implementing the Application Protocol Interface

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

---

**Creator**: @jessicadaugherty

**Comment by Olshansk** [comment]
Closing in place of the new approach outline [here](https://github.com/pokt-network/pocket/tree/main/utility/doc) for M3 task definition.
