### ISSUE TITLE
[DOCUMENT] Interfaces for the M3 Servicer Protocol

### ISSUE THREAD

**Issue by jessicadaugherty** [pokt-network/pocket-network-protocol#24]
## Objective

Code / document interfaces for the Service Node Protocol to enable servicer session participation and understanding around this piece of the M3 milestone.

## Origin Document

[M3 Milestone](https://github.com/pokt-network/pocket/blob/main/docs/roadmap/README.md#relay-protocol)

This is the first step into beginning the Service Node Protocol development.

Existing M3 Interfaces:

- [Relay Protocol](https://github.com/pokt-network/pocket/pull/306)
- [Session Protocol](https://github.com/pokt-network/pocket/pull/303)

## Goals

- Clear interface(s) that show the lifecycle of the service node protocol
- Clear documentation supporting the above

## Deliverable

- Coded interface(s)
- Documentation support

## Non-goals / Non-deliverables

- Implementation of the interface

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

**Creator**: @jessicadaugherty

**Comment by Olshansk** [comment]
Closing in place of the new approach outline [here](https://github.com/pokt-network/pocket/tree/main/utility/doc) for M3 task definition.
